fix WSE signature generation with password protected private key
slevomat/eet-client pull request #3
Opened 2016-11-21 16:36 UTC by jaygridley

2016-11-21 19:18 UTC, janlanger requested changes

2016-11-21 19:18 UTC, janlanger commented on tests/SlevomatEET/CryptographyServiceTest.php
> +	public function testWSESignature()
Test prosím rozdělit na dva - jeden pro validní heslo, druhý pro chybné heslo, ideálně přidat i třetí pro cert bez hesla.

2016-11-21 19:18 UTC, janlanger commented on tests/SlevomatEET/CryptographyServiceTest.php
> +		$request = "<?xml version=\"1.0\" encoding=\"UTF-8\"?><SOAP-ENV:Envelope xmlns:SOAP-ENV=\"http://schemas.xmlsoap.org/soap/envelope/\" xmlns:ns1=\"http://fs.mfcr.cz/eet/schema/v3\"><SOAP-ENV:Body><n
XML by bylo lepší v samostatném souboru s nahrazením proměnných přes nějaké placeholdery

2016-11-21 19:18 UTC, janlanger commented on tests/SlevomatEET/CryptographyServiceTest.php
> +		$this->expectException(\PHPUnit_Framework_Error::class);
Takhle je to moc obecné, prosím přidat ještě `expectExceptionMessage` s konkrétní chybou.

2016-11-22 20:30 UTC, pepakriz commented on tests/SlevomatEET/Cryptography/CZ00000019.template.3.1.xml
> +    <soap:Body>
Jenom drobnost. V ostatních xml souborech se odsazuje tabama. Chceme tady také? Ping @janlanger

2016-11-22 21:03 UTC, janlanger approved these changes

2016-11-22 21:03 UTC, janlanger commented
Merged as https://github.com/slevomat/eet-client/commit/a1108e725d8e4353a16bbddb1f9783ff886886fe, thanks!

2016-11-22 21:03 UTC, closed without merging

2016-11-22 21:04 UTC, janlanger commented on tests/SlevomatEET/Cryptography/CZ00000019.template.3.1.xml
> +    <soap:Body>
jj, to sem upravil :)